spring.application.name=mlink

spring.datasource.url=jdbc:postgresql://postsgresqlDB:5432/mlink
spring.datasource.username=postgres
spring.datasource.password=gylmar

server.address=0.0.0.0
server.port=4022

